services:
    Algolia\SearchBundle\Command\:
        resource: '../../Command'
        autowire: true
        autoconfigure: true

    Algolia\SearchBundle\Command\SearchImportCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $searchServiceForAtomicReindex: '@search.service_for_atomic_reindex'

    search.search_indexer_subscriber:
        class: Algolia\SearchBundle\EventListener\SearchIndexerSubscriber
        public: true
        arguments:
            - '@search.service'
            - [] # doctrine subscribed events
        tags:
            - { name: doctrine.event_listener, event: postPersist, connection: default }
            - { name: doctrine.event_listener, event: postUpdate, connection: default }
            - { name: doctrine.event_listener, event: preRemove, connection: default }
            - { name: doctrine_mongodb.odm.event_subscriber }

    search.client:
        class: Algolia\AlgoliaSearch\Api\SearchClient
        public: true
        lazy: true
        factory: ['Algolia\AlgoliaSearch\Api\SearchClient', 'create']
        arguments:
            $appId: '%env(ALGOLIA_APP_ID)%'
            $apiKey: '%env(ALGOLIA_API_KEY)%'

    Algolia\AlgoliaSearch\Api\SearchClient:
        alias: search.client

    Algolia\SearchBundle\SearchService:
        alias: search.service

    Algolia\SearchBundle\Settings\SettingsManager:
        alias: search.settings_manager

    custom_normalizer:
        class: Symfony\Component\Serializer\Normalizer\CustomNormalizer
        public: false
        tags:
            - { name: serializer.normalizer, priority: -800 }
